=== miguelMontiel/webserviceEjemplo/webservicetest/src/Test.xsd
<?xml version = "1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name = "ODM">
    	<xs:complexType>
      		<xs:sequence>
        		<xs:element name = "siniestros">
          			<xs:complexType>
            			<xs:sequence>
              				<xs:element name = "ID" type = "xs:integer"/>
              				<xs:element name = "placa" type = "xs:string">
                				<xs:complexType>
                  					<xs:sequence>
                    					<xs:element name = "num_placa" type = "xs:integer"/>
                    					<xs:element name = "evento_placa" type = "xs:integer"/>
                    					<xsl:variable name = "precalificado_placa"/> 
                  					</xs:sequence>
                				</xs:complexType>
              				</xs:element>
              				<xs:element name = "serie" type = "xs:string">
                				<xs:complexType>
                  					<xs:sequence>
                    					<xs:element name = "num_serie" type = "xs:integer"/>
                    					<xs:element name = "evento_serie" type = "xs:integer"/>
										<xsl:variable name = "precalificado_serie"/> 
                  					</xs:sequence>
                				</xs:complexType>
              				</xs:element>
              				<xs:element name = "contratante" type = "xs:string">
                				<xs:complexType>
                  					<xs:sequence>
                    					<xs:element name = "rfc_contratante" type = "xs:string"/>
                    					<xs:element name = "evento_contratante" type = "xs:integer"/>
                    					<xsl:variable name = "precalificado_contratante"/> 
                  					</xs:sequence>
                				</xs:complexType>
              				</xs:element>
              				<xs:element name = "conductor" type = "xs:string">
                				<xs:complexType>
                  					<xs:sequence>
                    					<xs:element name = "rfc_conductor" type = "xs:string"/>
                    					<xs:element name = "evento_conductor" type = "xs:integer"/>
                    					<xsl:variable name = "precalificado_conductor"/> 
                  					</xs:sequence>
                				</xs:complexType>
              				</xs:element>
            			</xs:sequence>
          			</xs:complexType>
        		</xs:element>

        		<xs:element name = "tabla_placa">
        			<xa:complexType>
        				<xs:sequence>
        					<xs:element name = "placa"/>
        				</xs:sequence>
        			</xa:complexType>
        		</xs:element>

        		<xs:element name = "tabla_serie">
        			<xa:complexType>
        				<xs:sequence>
        					<xs:element name = "serie"/>
        				</xs:sequence>
        			</xa:complexType>
        		</xs:element>

        		<xs:element name = "tabla_contratante">
        			<xa:complexType>
        				<xs:sequence>
        					<xs:element name = "contratante"/>
        				</xs:sequence>
        			</xa:complexType>
        		</xs:element>

        		<xs:element name = "tabla_conductor">
        			<xa:complexType>
        				<xs:sequence>
        					<xs:element name = "conductor"/>
        				</xs:sequence>
        			</xa:complexType>
        		</xs:element>

        		<xs:element name = "tabla_eventos">
        			<xa:complexType>
        				<xs:sequence>
        					<xs:element name = "evento"/>
        				</xs:sequence>
        			</xa:complexType>
        		</xs:element>
      		</xs:sequence>
    	</xs:complexType>
  	</xs:element>
</xs:schema>

=== miguelMontiel/webserviceEjemplo/webservicetest/src/Test.xml
<?xml version = "1.0"?>

<ODM  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation = "Test.xsd">
	<siniestros>
		<ID>Identificador: </ID>
		<placa>
			<num_placa>
				Número de Placa: 
			</num_placa>
			<evento_placa>
				Eventos en Placa:
			</evento_placa>
			<precalificado_placa>
				<!-- Variable -->
			</precalificado_placa>
		</placa>
		<serie>
			<num_serie>
				Número de Serie: 
			</num_serie>
			<evento_serie>
				Eventos en Serie:
			</evento_serie>
			<precalificado_serie>
				<!-- Variable -->
			</precalificado_serie>
		</serie>
		<contratante>
			<rfc_contratante>
				RFC del contratante:
			</rfc_contratante>
			<evento_contratante>
				Eventos del contratante:
			</evento_contratante>
			<precalificado_contratante>
				<!-- Variable -->
			</precalificado_contratante>
		</contratante>
		<conductor>
			<rfc_conductor>
				RFC del conductor:
			</rfc_conductor>
			<evento_conductor>
				Eventos del conductor:
			</evento_conductor>
			<precalificado_conductor>
				<!-- Variable -->
			</precalificado_conductor>
		</conductor>
	</siniestros>

	<tabla_placa>
		<placa>
		</placa>
	</tabla_placa>

	<tabla_serie>
		<serie>
		</serie>
	</tabla_serie>

	<tabla_contratante>
		<contratante>
		</contratante>
	</tabla_contratante>

	<tabla_conductor>
		<conductor>
		</conductor>
	</tabla_conductor>

	<tabla_eventos>
		<evento>
		</evento>
	</tabla_eventos>
</ODM>
